// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PrimitiveClash.Backend.Data;

#nullable disable

namespace PrimitiveClash.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251024200249_TowerTemplatesAdded")]
    partial class TowerTemplatesAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PrimitiveClash.Backend.Models.ArenaTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RequiredTrophies")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ArenaTemplates");
                });

            modelBuilder.Entity("PrimitiveClash.Backend.Models.Cards.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Damage")
                        .HasColumnType("integer");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<int>("ElixirCost")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string[]>("Targets")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Cards");

                    b.HasDiscriminator().HasValue("Card");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PrimitiveClash.Backend.Models.Deck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("PrimitiveClash.Backend.Models.PlayerCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DeckId")
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("DeckId");

                    b.HasIndex("UserId");

                    b.ToTable("PlayerCards");
                });

            modelBuilder.Entity("PrimitiveClash.Backend.Models.TowerTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Damage")
                        .HasColumnType("integer");

                    b.Property<int>("Hp")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("Range")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("TowerTemplates");
                });

            modelBuilder.Entity("PrimitiveClash.Backend.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Gems")
                        .HasColumnType("integer");

                    b.Property<int>("Gold")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Trophies")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PrimitiveClash.Backend.Models.Cards.BuildingCard", b =>
                {
                    b.HasBaseType("PrimitiveClash.Backend.Models.Cards.Card");

                    b.Property<int>("DamageArea")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer");

                    b.Property<float>("Duration")
                        .HasColumnType("real");

                    b.Property<float>("HitSpeed")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("real");

                    b.Property<int>("Hp")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer");

                    b.Property<int>("Range")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Building");
                });

            modelBuilder.Entity("PrimitiveClash.Backend.Models.Cards.SpellCard", b =>
                {
                    b.HasBaseType("PrimitiveClash.Backend.Models.Cards.Card");

                    b.Property<float>("Duration")
                        .HasColumnType("real");

                    b.Property<int>("Radius")
                        .HasColumnType("integer");

                    b.ToTable("Cards", t =>
                        {
                            t.Property("Duration")
                                .HasColumnName("SpellCard_Duration");
                        });

                    b.HasDiscriminator().HasValue("Spell");
                });

            modelBuilder.Entity("PrimitiveClash.Backend.Models.Cards.TroopCard", b =>
                {
                    b.HasBaseType("PrimitiveClash.Backend.Models.Cards.Card");

                    b.Property<int>("DamageArea")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer");

                    b.Property<float>("HitSpeed")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("real");

                    b.Property<int>("Hp")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer");

                    b.Property<string>("MovementSpeed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Range")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer");

                    b.Property<int>("VisionRange")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Troop");
                });

            modelBuilder.Entity("PrimitiveClash.Backend.Models.Deck", b =>
                {
                    b.HasOne("PrimitiveClash.Backend.Models.User", null)
                        .WithOne("Deck")
                        .HasForeignKey("PrimitiveClash.Backend.Models.Deck", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrimitiveClash.Backend.Models.PlayerCard", b =>
                {
                    b.HasOne("PrimitiveClash.Backend.Models.Cards.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrimitiveClash.Backend.Models.Deck", null)
                        .WithMany("PlayerCards")
                        .HasForeignKey("DeckId");

                    b.HasOne("PrimitiveClash.Backend.Models.User", null)
                        .WithMany("PlayerCards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("PrimitiveClash.Backend.Models.Deck", b =>
                {
                    b.Navigation("PlayerCards");
                });

            modelBuilder.Entity("PrimitiveClash.Backend.Models.User", b =>
                {
                    b.Navigation("Deck");

                    b.Navigation("PlayerCards");
                });
#pragma warning restore 612, 618
        }
    }
}
