// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PrimitiveClash.Backend.Data;

#nullable disable

namespace PrimitiveClash.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PrimitiveClash.Backend.Models.Cards.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CardType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<int>("Damage")
                        .HasColumnType("integer");

                    b.Property<int>("ElixirCost")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string[]>("Targets")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Cards");

                    b.HasDiscriminator<string>("CardType").HasValue("Card");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PrimitiveClashBackend.Models.PlayerCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("PlayerCards");
                });

            modelBuilder.Entity("PrimitiveClash.Backend.Models.Cards.BuildingCard", b =>
                {
                    b.HasBaseType("PrimitiveClash.Backend.Models.Cards.Card");

                    b.Property<int>("DamageArea")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer");

                    b.Property<float>("Duration")
                        .HasColumnType("real");

                    b.Property<float>("HitSpeed")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("real");

                    b.Property<int>("Hp")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer");

                    b.Property<int>("Range")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Building");
                });

            modelBuilder.Entity("PrimitiveClash.Backend.Models.Cards.SpellCard", b =>
                {
                    b.HasBaseType("PrimitiveClash.Backend.Models.Cards.Card");

                    b.Property<float>("Duration")
                        .HasColumnType("real");

                    b.Property<int>("Radius")
                        .HasColumnType("integer");

                    b.ToTable("Cards", t =>
                        {
                            t.Property("Duration")
                                .HasColumnName("SpellCard_Duration");
                        });

                    b.HasDiscriminator().HasValue("Spell");
                });

            modelBuilder.Entity("PrimitiveClash.Backend.Models.Cards.TroopCard", b =>
                {
                    b.HasBaseType("PrimitiveClash.Backend.Models.Cards.Card");

                    b.Property<int>("DamageArea")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer");

                    b.Property<float>("HitSpeed")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("real");

                    b.Property<int>("Hp")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer");

                    b.Property<string>("MovementSpeed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Range")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Troop");
                });

            modelBuilder.Entity("PrimitiveClashBackend.Models.PlayerCard", b =>
                {
                    b.HasOne("PrimitiveClash.Backend.Models.Cards.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Card");
                });
#pragma warning restore 612, 618
        }
    }
}
